# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Policy
version:      1.005
version_from: lib/File/Policy.pm
installdirs:  site
requires:
    File::Slurp:                   0
    File::Spec::Functions:         0
    Log::Trace:                    0
    Test::Assertions:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
